package com.pulse.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    BAD_REQUEST,
    EMAIL_ALREADY_IN_USE,
    USERNAME_ALREADY_IN_USE,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    USER_NOT_FOUND,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    PAYLOAD_TOO_LARGE,
    CHANNEL_NAME_TAKEN,
    MEMBER_ALREADY_EXISTS,
    INTERNAL_ERROR
}
