package com.pulse.realtime.dto;

public enum RealtimeEventType {
    MESSAGE_CREATED,
    MESSAGE_UPDATED,
    MESSAGE_DELETED,
    REACTION_ADDED,
    REACTION_REMOVED,
    TYPING,
    PRESENCE_CHANGED,
    NOTIFICATION_CREATED,
    DIRECT_MESSAGE_CREATED,
    DIRECT_MESSAGE_DELETED
}
